Repository doctrine/coding-standard, pull requests merged in 2018-04, with the labels that each got.

#49 Forbidden usage of compact
  lib/Doctrine/ruleset.xml
  tests/expected_report.txt
  tests/fixed/forbidden-functions.php
  tests/input/forbidden-functions.php
Labels: Improvement, RFC

#51 Enable UseSpacing sniff
  lib/Doctrine/ruleset.xml
  tests/expected_report.txt
  tests/fixed/namespaces-spacing.php
  tests/input/namespaces-spacing.php
Labels: New sniff

#50 Remove early return duplicated entry
  README.md
Labels: Improvement

#53 Use SemicolonSpacing Sniff
  lib/Doctrine/ruleset.xml
  tests/expected_report.txt
  tests/fixed/new_with_parentheses.php
  tests/fixed/semicolon_spacing.php
  tests/input/semicolon_spacing.php
Labels: Improvement, RFC

#54 Add Generic.Arrays.ArrayIndent sniff
  lib/Doctrine/ruleset.xml
  tests/expected_report.txt
  tests/fixed/array_indentation.php
  tests/input/array_indentation.php
Labels: Improvement, RFC
