Repository doctrine/coding-standard, pull requests merged in 2018-05, with the labels that each got.

#55 Use PHPCS XML schema definition
  lib/Doctrine/ruleset.xml
  phpcs.xml.dist
Labels: Improvement

#39 Add ShortList sniff
  composer.json
  lib/Doctrine/ruleset.xml
  tests/expected_report.txt
  tests/fixed/example-class.php
  tests/input/example-class.php
Labels: Improvement, New sniff

#59 Enable NamespaceSpacing sniff
  composer.json
  lib/Doctrine/ruleset.xml
  tests/expected_report.txt
Labels: New sniff, RFC

#61 Improve short list syntax rule description
  lib/Doctrine/ruleset.xml
Labels: Improvement
