Repository doctrine/coding-standard, pull requests merged in 2018-12, with the labels that each got.

#96 Link to Slack instead of Gitter
  docs/en/index.rst
Labels: documentation

#97 Disallow "Class <name>" as class comment
  lib/Doctrine/ruleset.xml
  tests/expected_report.txt
  tests/input/forbidden-comments.php
Labels: Improvement, New sniff

#98 Remove IDEA/Phpstorm default file template properly
  lib/Doctrine/ruleset.xml
  tests/expected_report.txt
  tests/input/forbidden-comments.php
Labels: Improvement

#52 Exclude Squiz.Commenting.FunctionComment.ThrowsNotCapital sniff
  lib/Doctrine/ruleset.xml
  tests/fixed/example-class.php
  tests/input/example-class.php
Labels: Improvement, RFC

#99 Update to PHPCS 3.4 and use new Sniffs
  composer.json
  lib/Doctrine/ruleset.xml
  tests/expected_report.txt
  tests/fixed/not_spacing.php
  tests/input/not_spacing.php
Labels: Improvement

#101 Use Ubuntu 16.04
  .travis.yml
Labels: Improvement
