Repository doctrine/coding-standard, pull requests merged in 2018-09, with the labels that each got.

#81 Update homepage
  composer.json
Labels: documentation

#80 Enable TraitUseDeclarationSniff & TraitUseSpacingSniff
  lib/Doctrine/ruleset.xml
  tests/expected_report.txt
  tests/fixed/traits-uses.php
  tests/input/traits-uses.php
Labels: New sniff

#82 Enable UselessConstantTypeHintSniff
  lib/Doctrine/ruleset.xml
  tests/expected_report.txt
  tests/fixed/constants-var.php
  tests/input/constants-var.php
Labels: New sniff

#85 Validate ruleset against XML schema
  .travis.yml
  lib/Doctrine/ruleset.xml
Labels: Improvement

#86 Document how to customize rules
  docs/en/reference/customizing.rst
  docs/en/reference/index.rst
  docs/en/sidebar.rst
Labels: Improvement, blocker, documentation

#77 Bump patch versions of dependencies
  composer.json
Labels: Improvement, release blocker

#88 phpDoc annotation spacing
  .travis.yml
  composer.json
  lib/Doctrine/ruleset.xml
  tests/expected_report.txt
  tests/fixed/doc-comment-spacing.php
  tests/input/doc-comment-spacing.php
Labels: New sniff

#89 Enable OptimizedFunctionsWithoutUnpacking sniff
  lib/Doctrine/ruleset.xml
  tests/expected_report.txt
  tests/fixed/optimized-functions.php
  tests/input/optimized-functions.php
Labels: New sniff

#84 Use new PHPCS array syntax
  composer.json
  lib/Doctrine/ruleset.xml
Labels: Improvement
