Repository doctrine/coding-standard, pull requests merged in 2018-03, with the labels that each got.

#32 Allow using doesNotPerformAssertions annotations
  lib/Doctrine/ruleset.xml
Labels: Improvement

#29 [RFC] Add SlevomatCodingStandard.PHP.TypeCast
  composer.json
  lib/Doctrine/ruleset.xml
Labels: Improvement, RFC, WIP

#34 Enable EmptyComment sniff
  lib/Doctrine/ruleset.xml
Labels: New sniff

#33 Bump PHPCS, fix BC break
  composer.json
  lib/Doctrine/ruleset.xml
Labels: bug

#36 Remove checkmark on unenforceable rule
  README.md
Labels: bug

#35 Enable RequireOneLinePropertyDocComment sniff
  lib/Doctrine/ruleset.xml
Labels: New sniff

#43 [RFC] Reference global classes via `use`
  lib/Doctrine/ruleset.xml
  tests/expected_report.txt
  tests/fixed/example-class.php
Labels: Improvement, New sniff, RFC

#45 Remove constraint version
  README.md
Labels: Improvement

#46 Forbidden usage of settype function
  lib/Doctrine/ruleset.xml
  tests/expected_report.txt
  tests/fixed/forbidden-functions.php
  tests/input/forbidden-functions.php
Labels: Improvement, RFC

#48 Forbidden usage of extract
  lib/Doctrine/ruleset.xml
  tests/expected_report.txt
  tests/fixed/forbidden-functions.php
  tests/input/forbidden-functions.php
Labels: Improvement, RFC
