Repository doctrine/coding-standard, pull requests merged in 2019-11, with the labels that each got.

#136 Require space before throw, yield and yield from
  composer.json
  lib/Doctrine/ruleset.xml
  tests/expected_report.txt
  tests/fixed/example-class.php
  tests/input/example-class.php
Labels: New rule

#137 Require space after Block Control Structures
  composer.json
  lib/Doctrine/ruleset.xml
  tests/expected_report.txt
  tests/fixed/example-class.php
  tests/input/example-class.php
Labels: Improvement

#133 Update documentation for v6
  .doctrine-project.json
Labels: documentation
