Repository doctrine/coding-standard, pull requests merged in 2019-02, with the labels that each got.

#108 Make all annotations useful by default
  lib/Doctrine/ruleset.xml
Labels: Improvement

#109 Upgrade to Slevomat CS 5.0
  composer.json
  lib/Doctrine/ruleset.xml
  tests/expected_report.txt
  tests/fixed/UselessConditions.php
Labels: Improvement

#111 Enable SpreadOperatorSpacing sniff
  lib/Doctrine/ruleset.xml
  tests/expected_report.txt
  tests/fixed/spread-operator.php
  tests/input/spread-operator.php
Labels: New sniff

#112 Forbid LSB for constants
  lib/Doctrine/ruleset.xml
  tests/expected_report.txt
  tests/fixed/constants-no-lsb.php
  tests/input/constants-no-lsb.php
Labels: New sniff

#114 Forbid "Trait" suffix
  lib/Doctrine/ruleset.xml
  tests/expected_report.txt
  tests/fixed/superfluous-naming.php
  tests/input/superfluous-naming.php
Labels: New sniff

#115 Trigger CI failure when phpcbf cannot fix the file
  .travis.yml
Labels: Improvement

#38 Forbid prefix too
  docs/en/reference/index.rst
  lib/Doctrine/ruleset.xml
Labels: documentation
