Repository doctrine/coding-standard, pull requests merged in 2020-06, with the labels that each got.

#194 Update tests expectations based on bugfix in dependencies
  composer.json
  tests/expected_report.txt
  tests/fixed/ControlStructures.php
  tests/php-compatibility.patch
Labels: Improvement

#205 Update PSR-2 refs on docs to PSR-12
  docs/en/reference/customizing.rst
  docs/en/reference/index.rst
Labels: documentation

#210 Fix exit code handling
  Makefile
  tests/expected_report.txt
  tests/php-compatibility.patch
Labels: CI, bug
