Repository doctrine/coding-standard, pull requests merged in 2020-05, with the labels that each got.

#184 Fix documentation version numbers and labels
  .doctrine-project.json
Labels: documentation

#182 update to latest shivammathur/setup-php Github Action
  .github/workflows/continuous-integration.yml
Labels: CI

#175 Add rule to ensure Arrow Functions declaration format
  lib/Doctrine/ruleset.xml
  tests/expected_report.txt
  tests/fixed/arrow-functions-format.php
  tests/input/arrow-functions-format.php
  tests/php-compatibility.patch
Labels: New rule
