Repository doctrine/coding-standard, pull requests merged in 2020-02, with the labels that each got.

#154 Use `NegationOperatorSpacingSniff` to ensure no space before `-`
  composer.json
  lib/Doctrine/ruleset.xml
  tests/fixed/negation-operator.php
  tests/input/negation-operator.php
  tests/php-compatibility.patch
Labels: New rule

#155 Use `SingleLineArrayWhitespace` to ensure single line arrays spacing
  lib/Doctrine/ruleset.xml
  tests/fixed/single-line-array-spacing.php
  tests/input/single-line-array-spacing.php
  tests/php-compatibility.patch
Labels: New rule

#157 Improve diff while running `test-fix`
  Makefile
Labels: Improvement

#153 Enhancement: Add workflow for GitHub Actions
  .docker/validate-against-schema/Dockerfile
  .gitattributes
  .github/workflows/continuous-integration.yml
  README.md
Labels: CI, Improvement

#159 Normalize documentation comments
  lib/Doctrine/ruleset.xml
Labels: Improvement

#151 Remove usless interface and trait comments
  lib/Doctrine/ruleset.xml
  tests/fixed/forbidden-comments.php
  tests/input/forbidden-comments.php
  tests/php-compatibility.patch
Labels: Improvement

#160 Introduce Dependabot
  .dependabot/config.yml
  composer.json
Labels: Dependencies, Improvement

#161 Remove PHP 8 from GitHub Actions
  .github/workflows/continuous-integration.yml
Labels: CI
