Repository doctrine/coding-standard, pull requests merged in 2020-04, with the labels that each got.

#171 Introduce rule requiring Null Coalesce Equal Operator
  lib/Doctrine/ruleset.xml
  tests/expected_report.txt
  tests/fixed/null_coalesce_equal_operator.php
  tests/input/null_coalesce_equal_operator.php
  tests/php-compatibility.patch
Labels: New rule

#170 Improve diff while running `test-report`
  Makefile
Labels: Improvement

#169 Ensure that spacing around `cases` are consistent
  lib/Doctrine/ruleset.xml
  tests/fixed/ControlStructures.php
  tests/input/ControlStructures.php
  tests/php-compatibility.patch
Labels: Improvement

#174 Add rule forbidding more than one constant declared per statement
  lib/Doctrine/ruleset.xml
  tests/expected_report.txt
  tests/fixed/constants-var.php
  tests/input/constants-var.php
  tests/php-compatibility.patch
Labels: New rule

#178 Fix warnings on Travis CI configuration file
  .travis.yml
Labels: CI

#176 Remove dead sniffs autoload
  composer.json
Labels: Improvement
