Repository doctrine/coding-standard, pull requests merged in 2023-04, with the labels that each got.

#310 Disallow string property fetch
  composer.json
  lib/Doctrine/ruleset.xml
  tests/expected_report.txt
  tests/fixed/string_property_fetch.php
  tests/input/string_property_fetch.php
  tests/php72-compatibility.patch
  tests/php73-compatibility.patch
  tests/php74-compatibility.patch
  tests/php80-compatibility.patch
Labels: New rule

#316 Lint Dockerfile files with Hadolint
  .docker/validate-against-schema/Dockerfile
  .github/workflows/ci-dockerfile.yml
Labels: CI

#315 Lint shell scripts with ShellCheck
  .github/workflows/ci-shell-scripts.yml
Labels: CI

#319 Remove duplicate `RequireOneLineDocComment` rule
  lib/Doctrine/ruleset.xml
Labels: bug
